### ISSUE TITLE
[Mostro] Rust Developer

### ISSUE THREAD

**Issue by Cli5y** [Bitcoin-Product-Community/opportunities#11]
_Opportunity expired until clarity on whether these positions are paid or not._

# Project Details
Project name: Mostro
Project summary: Mostro is a censorship-resistant, and non-custodial lightning network, peer-to-peer exchange without single points of failure.
Is it open-source?: Yes
Role: Rust Developer

# Team Dynamics
About how many core contributors are involved? What are their roles? 1 core developer and various open-source contributors.

What are the communication mediums? Telegram for day-to-day communications. Other mediums are Twitter and Nostr.

What stage is the project in? Alpha

How long has it been running for? 7 months

What are the goals of the project? The goal of this project is to create a non-custodial, peer-to-peer exchange on the lightning network without a single point of failure. After creating the popular @lnp2pBot on telegram, the team saw an opportunity to build a similar solution on Nostr that is censorship resistant.

Do you have any regular meetings? If so, what time, when, and where are they? The team is currently working async.

What timezone are your contributors in? Global

What the project needs in general? The project is seeking Rust developers to help build the project from the ground up. There's an opportunity to make a big impact.

# About the Role
What specific role(s) or skill(s) are you looking for? Rust developers.
How many hours a week minimum will they need to commit and for how long? 2 hours a week minimum. 
Is this a paid position? No.
What can the contributor expect when onboarding to your project? Join our telegram to get started. Happy hacking!

# How to Connect
If a contributor is interested, how should they get involved? Join our telegram [group](https://t.me/mostro_dev).

**Comment by NIKU-SINGH** [comment]
Hey could you tell me more about what level of experience are you looking for in Rust?

**Comment by ecurrencyhodler** [comment]
@esepibito are you a company that's building this P2P exchange with the hopes of earning $$? If so, this should really be a paid position.

**Comment by Cli5y** [comment]
@NIKU-SINGH dm'd you on twitter

**Comment by Cli5y** [comment]
@ecurrencyhodler clarified in dm's.
