### ISSUE TITLE
Citadel OS - UI/UX Designer

### ISSUE THREAD

**Issue by pippellia-btc** [Bitcoin-Product-Community/opportunities#12]
# Project Details
Project name: Citadel OS / Nirvati OS
Project summary (~5 sentences): We make it simple for anyone to run their own node & personal servers so they can become self-sovereign. TLDR; Citadel is like Umbrel, but FOSS and better.
Is it open-source?: proudly FLOSS
Role: UI/UX Designer

# Team Dynamics
About how many core contributors are involved? What are their roles?
1 core dev and founder, 1 project janitor.

What are the communication mediums? telegram, (rarely gitlab)
What stage is the project in? alpha release
How long has it been running for? > 2 years
What are the goals of the project? We want to make Citadel the most stable and reliable OS for running nodes, as well as adding crucial features like https, setting and logs for all apps and multi-user support. Secondly, we want to add more Apps, both bitcoin focused and not. This requires improving the existing UI/UX as well as creating new ones from scratch.
Do you have any regular meetings? Not at the moment, we do async communication.
What timezone are your contributors in? UTC+2
What the project needs in general? Citadel needs to become more stable, but it also needs to become easier to use from a UI/UX perspective. Being easy and simple to use by the average person is central to the project.

# About the Role
What specific role(s) or skill(s) are you looking for?
How many hours a week minimum will they need to commit and for how long? 5h minimum
Is this a paid position? Nope
What can the contributor expect when onboarding to your project? To become part of one of the projects with the greatest potential for impact. After "not your keys, not your coins" by importance there is only "not your node, not your rules". You can also expect to have a great deal of freedom for work schedules, workload and what to focus on.

# How to Connect
If a contributor is interested, how should they get involved? Here are two examples:
+ Reach out via twitter @runcitadel

**Comment by Middy-Technologies** [comment]
I'm interested in joining the team, I'm a professional UI/UX designer with over 2 years of practicing experience, I'll like to contribute to this interesting project, kindly contact me via mail: abdulhamidoyekunle@gmail.com, I'll be expecting your response soon.

**Comment by Retr6** [comment]
Hello, I would love to contribute to the growth of this project with my product design skills and experience. Check out my portfolio femikolade.com. You can also reach out to me via twitter @kaizeroj  or telegram @retr6.
Thank you, Satoshi.
