### ISSUE TITLE
[BITCOIN ACCESSIBILITY] PRODUCT MANAGER

### ISSUE THREAD

**Issue by aassoiants** [Bitcoin-Product-Community/opportunities#3]
# Project Details
Project name: Bitcoin Accessibility
Project summary (~5 sentences): Virtually all bitcoin wallets have accessibility issues. Around 8% of the population have accessibility needs. Up to 25% of general users benefit from improvements in accessibility. This project is a methodological improvement of accessibility across bitcoin wallets. 
Is it open-source?: Yes
Role: Accessibility Coordinator

# Team Dynamics
About how many core contributors are involved? What are their roles?
- 2: User designer and user researcher

What are the communication mediums? Discord
What stage is the project in? Early-mid
How long has it been running for? Less than a year
What are the goals of the project? Improve accessibility of open source bitcoin wallets
Do you have any regular meetings? TBD
What timezone are your contributors in? Central europe
What the project needs in general? Coordinating the testing, documentation, and fixing of accessibility issues in open source bitcoin wallest and software

# About the Role
What specific role(s) or skill(s) are you looking for?
- Project management, relationship management, design skills

How many hours a week minimum will they need to commit and for how long? 5-10
Is this a paid position? No
What can the contributor expect when onboarding to your project? The testing plan has been laid out. We'd like their help coordinating the steps, communications with projects and practitioners. 

# How to Connect
If a contributor is interested, how should they get involved? Here are two examples: DM christoph on discord.

**Comment by ecurrencyhodler** [comment]
I've reached out to christoph and have taken on this issue!
