### ISSUE TITLE
[BITCOIN OPTECH/ COMPATIBILITY DASHBOARD] PRODUCT MANAGER

### ISSUE THREAD

**Issue by aassoiants** [Bitcoin-Product-Community/opportunities#4]
# Project Details
Project name: Bitcoin Optech/ Compatibility Dashboard
Project summary (~5 sentences): The Bitcoin Optech [Compatability Dashboard](https://bitcoinops.org/en/compatibility/) needs maintenance, upkeep, and updates. 
Is it open-source?: Yes
Role: *Examples including product manager, marketer, community builder, etc. Add an appropriate label if it is available as well.*

# Team Dynamics
About how many core contributors are involved? What are their roles?
- 5: Compatibility Matrix creator + newsletter editors

What are the communication mediums? TBD
What stage is the project in? Maintenance
How long has it been running for? >4 years
What are the goals of the project? Compatibility Dashboard is modern and updated with latest info. Software users know which tech user which software. Tech is rewarded or punished for adhering or not to best practices. 
Do you have any regular meetings? TBD
What timezone are your contributors in? TBD
What the project needs in general? Project management and maintenance

# About the Role
What specific role(s) or skill(s) are you looking for? Project management and maintenance
How many hours a week minimum will they need to commit and for how long? 5-10hrs/week
Is this a paid position? No
What can the contributor expect when onboarding to your project? More hours at the start, steadying out past the first month 

# How to Connect
If a contributor is interested, how should they get involved? ecurrencyhodler will introduce to Mike Schmidt.

**Comment by ecurrencyhodler** [comment]
Steve Torok has been introduced to Mike Schmidt for this initiative.
