### ISSUE TITLE
[SEEDSIGNER] ISSUE & TICKER ORGANIZER

### ISSUE THREAD

**Issue by aassoiants** [Bitcoin-Product-Community/opportunities#5]
# Project Details
Project name: Seedsigner
Project summary: Bitcoin-only open source do-it-yourself hardware wallet
Is it open-source?: Yes
Role: Issue & Ticket organizer, Product Manager

# Team Dynamics
About how many core contributors are involved? What are their roles?
-8: devs, UI designers, etc

What are the communication mediums? TBD
What stage is the project in? Stable release
How long has it been running for? >2 years
What are the goals of the project? Seedsigner hardware at scale at the lowest possible cost
Do you have any regular meetings? TBD
What timezone are your contributors in? TBD
What the project needs in general? Project manage by reviewing github and telegram issues and tickets

# About the Role
What specific role(s) or skill(s) are you looking for? Organization skills, consistency, ability to create and organize tickets and issues
How many hours a week minimum will they need to commit and for how long? 5-10 hours a week.
Is this a paid position? No
What can the contributor expect when onboarding to your project? Onboarding process and some training

# How to Connect
If a contributor is interested, how should they get involved? Reach out to [seedsigner](https://twitter.com/SeedSigner) on twitter.

**Comment by ecurrencyhodler** [comment]
@bitcoinprecept has taken on this issue. Here's an update from keith from seedsigner: https://twitter.com/bitcoin_product/status/1663655721680904193
