### ISSUE TITLE
[BITCOIN DEV KIT] PRODUCT MANAGER

### ISSUE THREAD

**Issue by aassoiants** [Bitcoin-Product-Community/opportunities#6]
# Project Details
Project name: Bitcoin Development Kit
Project summary (~5 sentences): BDK trying to make it easy for anyone to create a mobile wallet. Library + language bindings. On chain only. Bitcoin wallets.
Is it open-source?: Yes
Role: Product Manager

# Team Dynamics
About how many core contributors are involved? What are their roles?
- 7, mostly devs

What are the communication mediums? Discord, signal, github projects
What stage is the project in? Pre 1.0
How long has it been running for? >3 years
What are the goals of the project? Product management
Do you have any regular meetings? Yes - biweekly. Every week together. 
What timezone are your contributors in? TBD
What the project needs in general? Product management

# About the Role
What specific role(s) or skill(s) are you looking for? Ideally is a technical Product Manager with knowledge of bitcoin and the team. Ideally is bitcoin only. Someone who knows rust. Know github. Know bitcoin protocol stuff. Need to not be a shitcoiner. Also have non-rust developers. Know how to understand issues and assign them.

How many hours a week minimum will they need to commit and for how long? At least 3 hours a week for ideally minimum 2 years
Want them to be on discord and answering the team. Prepare and put on the call they have biweekly. This is where they go through backlog and address any issues/pr’s that need to be addressed. Which pr’s are going to make and not going to make it. 
It’ll take 2 hours to prepare. 1 hour to do the hour.

Ideally commit to at least 2 years. 

Is this a paid position? No
What can the contributor expect when onboarding to your project? Could get into this role in small ways. Then get more involved gradually. Other examples is to help champion a feature too.
Meet with Steve to talk about. 
Ideal way is to have someone to get to PM issue tag. They comment. Then hop on a call with steve, then they take on small tasks.

# How to Connect
If a contributor is interested, how should they get involved? ecurrencyhodler will introduce them to Steve at BDK.

**Comment by ecurrencyhodler** [comment]
Manuel has volunteered to take on this position and I have introduced him to Steve. He is being onboarded onto the project.
